name: Compile Sketches
on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout custom library
        uses: actions/checkout@v3
        with:
          repository: gavinlyonsrepo/TM1638plus
          ref: master
          path: CustomLibrary # must contain string "Custom"
          # No need to put "Custom" library in the required-libraries list
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:       
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - darkroom_timer
          libraries: |
            - Arduino_Math
            - Arduino_EEPROM
