name: Compile Sketches
on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with: 
          required-libraries: TM1638plus
          sketch-paths: |
            # Configure the action to search all folders under the root of the repository for sketches and compile them.
            # This is formatted as a YAML list, which makes it possible to have multiple sketch paths if needed.
            - darkroom_timer
          libraries: |
